# node-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list-node
  template:
    metadata:
      labels:
        app: todo-list-node
    spec:
      containers:
      - name: todo-list-app
        image: amartinez8929/todo-list-app:latest
        ports:
        - containerPort: 3000
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql_root_password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql_database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql_password
          - name: CUSTOMERS_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: customers_host
