# secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql_root_password: cm9vdF9wYXNzd29yZA==
  mysql_user: ZGF0YWJhc2VfdXNlcg==
  mysql_password: ZGF0YWJhc2VfdXNlcl9wYXNzd29yZA==
